merge_protections_settings:
  reporting_method: deployments
  post_comment: false

queue_rules:
  - name: default
    queue_conditions:
      - base = main
    merge_conditions:
      - "#approved-reviews-by >= 1"

commands_restrictions:
  queue:
    conditions:
      - sender = ph1shingvic
